# Generated by Django 4.1.3 on 2023-03-10 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_de_criacao', models.DateField()),
                ('site', models.URLField()),
                ('numero_de_premiacoes', models.IntegerField()),
                ('estilo_musical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.estilomusical')),
                ('musicos', models.ManyToManyField(to='music.musico')),
            ],
        ),
    ]
