# Generated by Django 4.1.3 on 2023-03-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='musico',
            name='genero',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Woman'), ('O', 'Other')], max_length=1),
        ),
    ]
